### ISSUE TITLE
how to use this plugin

### ISSUE THREAD

**Issue by kaybinwong** [Dreamvention/2_d_social_login#1]
hi, i am a newer.
how to use this plugin?

**Comment by Dreamvention** [comment]
Hi - you need to install it like any other opencart extension and go to admin/extensions/social login and then to instructions tab - there you will find information how to set up the social logins

**Comment by kaybinwong** [comment]
but i can not see nothing at any page.

**Comment by kaybinwong** [comment]
but i can not see nothing at any front page.

**Comment by demartini** [comment]
+1

**Comment by a4ankii** [comment]
I have added  this  module for the opencart version 2.0.3.1 .It was working fine few days ago.but it stopped working suddenly tomorrow.can you please let me know what is the issue? please reply as soon as possible

**Comment by robbinhank** [comment]
Do you solve the problem? Is it can normally use? @a4ankii

**Comment by php5drvn** [comment]
Hi all install extension with shopunity.net and you will be abble to update.
